const GETALLTODOS = "GET_ALL_TODOS";
const POSTTODO = "POST_TODO";
const PUTTODO = "PUT_TODO";
const DELETETODO = "DELETE_TODO";
const GETTODOBYID = "GET_TODO_BY_ID";
const DATARESET = "DATA_RESET"

export { GETALLTODOS, POSTTODO, PUTTODO, DELETETODO, GETTODOBYID, DATARESET };
